function F = MooringTensionSeabed(x, L, omega, EA, x_F, z_F, C_B)
% Bestimmt die am Fairlead angreifende Vertikal- (V_F) und 
% Horizontalkraft (H_F)
% V_F == x(1); H_F == x(2)
% L == total unstretched length; omega == weight in fluid per unit length
% EA == extensional stiffness; C_B == coefficient of seabed static friction
%
% Theorie siehe Jonkman PhD S.35ff
%
F = [L-x(1)/omega+x(2)/omega*log(x(1)/x(2)+sqrt(1+(x(1)/x(2))^2)) + ...
     x(2)*L/EA + C_B*omega/2/EA*(-(L-x(1)/omega)^2 + ...
     (L-x(1)/omega-x(2)/C_B/omega)*max(L-x(1)/omega-x(2)/C_B/omega,0)) - x_F;
     x(2)/omega*(sqrt(1+(x(1)/x(2))^2)-1) + ...
     1/EA*(x(1)^2/2/omega) - z_F];
 %F = [L-x(1)/omega+x(2)/omega*log(x(1)/x(2)+sqrt(1+(x(1)/x(2))^2)) + ...
  %   x(2)*L/EA + C_B*omega/2/EA*(-(L-x(1)/omega)^2 + ...
   %  (L-x(1)/omega-x(2)/C_B/omega)*max(L-x(1)/omega-x(2)/C_B/omega,0)) - x_F;
    % x(2)/omega*(sqrt(1+(x(1)/x(2))^2)-sqrt(1+((x(1)-omega*L)/x(2))^2)) + ...
     %1/EA*(x(1)*L-omega*L^2/2) - z_F];